# -*- coding: utf-8 -*-
"""model cotton rf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPXCZwbKIr1AAp4r4TcoyZZe5w-x_9MH
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks"

import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import shutil
from PIL import Image

os.listdir("Cotton Disease/")

# Define the number of trees in the Random Forest
num_trees = 100

# Define function to load and preprocess images + show results
def load_and_preprocess_images(image_paths, show_example=True):
    preprocessed_images = []

    # batasi contoh tampilan 3 gambar saja
    max_preview = 3
    preview_count = 0

    for image_path in image_paths:
        image = Image.open(image_path)

        # --- TAMPILKAN GAMBAR ASLI ---
        if show_example and preview_count < max_preview:
            plt.figure(figsize=(4,4))
            plt.imshow(image)
            plt.title("Original Image")
            plt.axis("off")
            plt.show()

            print("Original array shape:", np.array(image).shape)
            print("Original array sample (5 pixels):")
            print(np.array(image).reshape(-1, 3)[:5])
            print("-" * 50)

        # Resize
        image_resized = image.resize((224, 224))

        # --- TAMPILKAN HASIL RESIZE ---
        if show_example and preview_count < max_preview:
            plt.figure(figsize=(4,4))
            plt.imshow(image_resized)
            plt.title("Resized Image (224x224)")
            plt.axis("off")
            plt.show()

            print("Resized array shape:", np.array(image_resized).shape)
            print("Resized array sample (5 pixels):")
            print(np.array(image_resized).reshape(-1, 3)[:5])
            print("-" * 50)

        # Normalize
        image_normalized = np.array(image_resized) / 255.0

        # --- TAMPILKAN HASIL NORMALISASI ---
        if show_example and preview_count < max_preview:
            print("Normalized pixel sample (5 values):")
            print(image_normalized.reshape(-1, 3)[:5])
            print("Min pixel value:", image_normalized.min())
            print("Max pixel value:", image_normalized.max())
            print("=" * 80)

        preprocessed_images.append(image_normalized)

        preview_count += 1

    preprocessed_images = np.array(preprocessed_images)
    preprocessed_images = preprocessed_images.reshape(preprocessed_images.shape[0], -1)

    return preprocessed_images

# Define function for local model training
def local_train(X_local, y_local):
    clf = RandomForestClassifier(n_estimators=num_trees, random_state=42)
    clf.fit(X_local, y_local)
    return clf

# Define function for model evaluation
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    y_pred_proba = model.predict_proba(X_test)
    return accuracy, y_pred, y_pred_proba

data = "Cotton Disease"
# Define paths to the train, test, and val directories
train_path = 'Cotton Disease/train'
test_path = 'Cotton Disease/test'
val_path = 'Cotton Disease/val'
# Define the path to the combined directory
combined_path = 'Cotton Disease/combined_dataset'

# Create the combined directory if it doesn't exist
os.makedirs(combined_path, exist_ok=True)
# Function to copy images from source directory to destination directory
def copy_images(source_dir, dest_dir):
    for subdir in os.listdir(source_dir):
        subdir_path = os.path.join(source_dir, subdir)
        if os.path.isdir(subdir_path):
            for file in os.listdir(subdir_path):
                file_path = os.path.join(subdir_path, file)
                if os.path.isfile(file_path):
                    dest_subdir_path = os.path.join(dest_dir, subdir)
                    os.makedirs(dest_subdir_path, exist_ok=True)
                    try:
                        shutil.copy(file_path, os.path.join(dest_subdir_path, file))
                        print(f"Successfully copied: {file_path}")
                    except Exception as e:
                        print(f"Error copying file: {file_path}, Error: {e}")
# Copy images from train directory
copy_images(train_path, combined_path)

# Copy images from test directory
copy_images(test_path, combined_path)

# Copy images from val directory
copy_images(val_path, combined_path)

print("Images combined successfully.")

# Directory containing the dataset
dataset_dir = "Cotton Disease/combined_dataset"

os.listdir(dataset_dir)

# List of classes (subdirectories) in the dataset directory
classes = os.listdir(dataset_dir)

# Combine all data from different classes
X, y = [], []
for class_name in classes:
    class_dir = os.path.join(dataset_dir, class_name)
    image_files = os.listdir(class_dir)
    for image_file in image_files:
        image_path = os.path.join(class_dir, image_file)
        X.append(image_path)
        y.append(class_name)

# Convert class labels to numeric labels
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Load and preprocess images for the training set
X_train_processed = load_and_preprocess_images(X_train)

# Train the local model
local_model = local_train(X_train_processed, y_train)

# Load and preprocess images for the testing set
X_test_processed = load_and_preprocess_images(X_test)

# Evaluate the local model
accuracy, y_pred, y_pred_proba = evaluate_model(local_model, X_test_processed, y_test)
print(f"Local Model Accuracy: {accuracy * 100:.2f}%")

# Generate classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Generate confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# ================================
# FUNGSI PREDIKSI 1 GAMBAR
# ================================

def predict_single_image(image_path):
    # Load image
    image = Image.open(image_path)

    # Preprocess sama seperti training
    image = image.resize((224, 224))
    image = np.array(image) / 255.0
    image = image.reshape(1, -1)  # reshape ke 2D (1, fitur)

    # Prediksi
    pred_label = local_model.predict(image)[0]
    pred_class = label_encoder.inverse_transform([pred_label])[0]

    # Tampilkan hasil
    plt.imshow(Image.open(image_path))
    plt.axis('off')
    plt.title(f"Prediction : {pred_class}")
    plt.show()

    return pred_class

# ================================
# UPLOAD GAMBAR UNTUK DI-TEST
# ================================

from google.colab import files

print("Upload 1 gambar daun kapas untuk prediksi:")
uploaded = files.upload()

for filename in uploaded.keys():
    file_path = filename
    print(f"File uploaded: {file_path}")

    # Prediksi gambar
    hasil = predict_single_image(file_path)
    print("Prediksi model:", hasil)

# ================================
# UPLOAD GAMBAR UNTUK DI-TEST
# ================================

from google.colab import files

print("Upload 1 gambar daun kapas untuk prediksi:")
uploaded = files.upload()

for filename in uploaded.keys():
    file_path = filename
    print(f"File uploaded: {file_path}")

    # Prediksi gambar
    hasil = predict_single_image(file_path)
    print("Prediksi model:", hasil)

# ================================
# UPLOAD GAMBAR UNTUK DI-TEST
# ================================

from google.colab import files

print("Upload 1 gambar daun kapas untuk prediksi:")
uploaded = files.upload()

for filename in uploaded.keys():
    file_path = filename
    print(f"File uploaded: {file_path}")

    # Prediksi gambar
    hasil = predict_single_image(file_path)
    print("Prediksi model:", hasil)